[package]
name = "computer-graphics-v3"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 3
debug = false

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"

[dependencies]
rand = "0.9.2"
raylib = "5.5.1"